name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install torch==1.8.1 --extra-index-url https://download.pytorch.org/whl/cu116
      - name: Test with pytest
        run: pytest tests